PKINIT DEFINITIONS EXPLICIT TAGS ::=
BEGIN
--EXPORTS ALL--
IMPORTS
KerberosTime, PrincipalName, Realm, EncryptionKey
FROM KerberosV5Spec2
{ iso(1) identified-organization(3) dod(6) internet(1) security(5) 
		 kerberosV5(2) };
-- Different from [RFC4556] Appendix A

AuthPack_OLD::= SEQUENCE {
	pkAuthenticator  [0] PKAuthenticator_OLD
} 
		
--
-- PK-AUTHENTICATOR - Different from [RFC4556]
-- Appendix A, PKAuthenticator.
--
PKAuthenticator_OLD::= SEQUENCE {
	kdc-name   [0] PrincipalName,
	kdc-realm  [1] Realm,
-- name and realm of the KDC issuing the ticket
	cusec      [2] INTEGER,
	ctime      [3] KerberosTime,
	nonce      [4] INTEGER
}


--
-- KERB-REPLY-KEY-PACKAGE - Different from [RFC4556]
-- Appendix A, ReplyKeyPack
--
KERB-REPLY-KEY-PACKAGE ::= SEQUENCE {
	replyKey [0] EncryptionKey,
-- Contains the session key used to encrypt the enc-part 
-- field in the AS-REP, for example, the AS reply key.
	
	
nonce [1] INTEGER,
-- binds response to the request; must be same as the nonce
-- passed in the PK-AUTHENTICATOR.
	...
} --#public-

END
